version: '3.8'

services:
  # PostgreSQL Veritabanı
  postgres:
    image: postgres:16
    container_name: docapp-postgres-db
    environment:
      POSTGRES_DB: docappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - docman-network

  # MinIO (S3 Compatible Storage)
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - docman-network

volumes:
  postgres_data:
  minio_data:

networks:
  docman-network:
    driver: bridge